version: 2
sources:
  - name: Olist_big_query
    schema: Olist_final_project
    description: raw data from big query 
    tables:
      - name: product
        identifier: products_en
        description: raw data for product with category and product_id
        columns:
          - name: product_id
            description: unique product identifier
          - name : product_category_name_english
            description: root category of product, translated in English
        tests:
          - unique:
              column_name: product_id
      - name: customers
        identifier: customers
        description: raw data for customer
        columns:
          - name: customer_unique_id
            description: primary key of the table
            tests:  
              - not_null
          - name: customer_id
            description: key to the orders dataset. Each order has a unique customer_i
          - name : customer_zip_code_prefix
            description : first five digits of customer zip code
          - name : customer_city
            description: customer city name
          - name: customer_state
            description : the state that the customer is located
      - name: geolocation
        identifier: geolocation_new
        description: raw data for geolocation
        columns:
          - name: geolocation_zip_code_prefix
            description: first 5 digits of zip code
          - name: geolocation_city
            description: the name of the city
          - name: geolocation_state
            description: state location name
      - name: order_items
        identifier: order_items
        description: raw data for order_items
        columns:
          - name: order_id
            description: order unique identifier
          - name: order_item_id
            description : sequential number identifying number of items included in the same order
          - name : product_id
            description: product unique identifier
          - name : seller_id
            description: seller unique identifier
          - name : shipping_limit_date
            description: Shows the seller shipping limit date for handling the order over to the logistic partner
          - name: price
            description: item_price
          - name : freight_value
            description: item freight value item (if an order has more than one item the freight value is splitted between items)
      - name: payments
        identifier: order_payments
        description: raw data for payments
        columns:
          - name: order_id
            description: unique identifier of an order.
          - name : payment_sequential
            description: a customer may pay an order with more than one payment method. If he does so, a sequence will be created to
          - name: payment_type
            description: method of payment chosen by the customer.
          - name : payment_installments
            description: number of installments chosen by the customer.
          - name : payment_value
            description: transaction value.
      - name: orders
        identifier: orders
        description: raw data for orders
        tests:
          - unique:
              column_name: order_id
        columns:
          - name: order_id
            description: unique identifier of the order.
          - name : customer_id
            description: key to the customer dataset. Each order has a unique customer_id.
          - name : order_status
            description: Reference to the order status (delivered, shipped, etc)
          - name: order_purchase_timestamp
            description: Shows the purchase timestamp.
          - name : order_approved_at
            description: Shows the payment approval timestamp.
          - name : order_delivered_carrier_date
            description: Shows the order posting timestamp. When it was handled to the logistic partner.
          - name : order_delivered_customer_date
            description: Shows the actual order delivery date to the customer
          - name : order_estimated_delivery_date
            description: Shows the estimated delivery date that was informed to customer at the purchase moment
      - name: reviews
        identifier: reviews
        description: raw data for reviews
        columns:
          - name: order_id
            description: unique order identifier
          - name : review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
      - name: sellers
        identifier: sellers
        description: raw data for selling
        columns:
          - name: seller_id
            description: seller unique identifier
          - name : seller_zip_code_prefix
            description: first 5 digits of seller zip code
          - name : seller_city
            description: seller city name
          - name : seller_state
            description: state location of the seller
      - name: turnover_map
        identifier: turnover_map
        description: data to create the map of Olist presence in Brazil by turnover
        columns:
          - name: turnover
            description: turnover of Olist 

      
models:
      - name: stg_Olist_big_query__customers
        description: staging data for customer
        columns:
          - name: customer_unique_id
            description: primary key of the table
          - name: customer_id
            description: key to the orders dataset. Each order has a unique customer_id
          - name : customer_zip_code_prefix
            description : first five digits of customer zip code
          - name : customer_city
            description: customer city name
          - name: customer_state
            description : the state that the customer is located
      - name: stg_Olist_big_query__geolocation
        description: staging data for geolocation
        columns:
          - name: geolocation_zip_code_prefix
            description: first 5 digits of zip code
          - name: geolocation_city
            description: the name of the city
          - name: geolocation_state
            description: state location name
      - name: stg_Olist_big_query__order_items
        description:  staging data for order_items
        columns:
          - name: order_id
            description: order unique identifier
          - name: order_item_id
            description : sequential number identifying number of items included in the same order
          - name : product_id
            description: product unique identifier
          - name : seller_id
            description: seller unique identifier
          - name : shipping_limit_date
            description: Shows the seller shipping limit date for handling the order over to the logistic partner
          - name: price
            description: item_price
          - name : freight_value
            description: item freight value item (if an order has more than one item the freight value is splitted between items)
      - name: stg_Olist_big_query__orders
        description: staging data for orders
        columns:
          - name: order_id
            description: unique identifier of the order.
          - name : customer_id
            description: key to the customer dataset. Each order has a unique customer_id.
          - name : order_status
            description: Reference to the order status (delivered, shipped, etc)
          - name: order_purchase_timestamp
            description: Shows the purchase timestamp.
          - name : order_approved_at
            description: Shows the payment approval timestamp.
          - name : order_delivered_carrier_date
            description: Shows the order posting timestamp. When it was handled to the logistic partner.
          - name : order_delivered_customer_date
            description: Shows the actual order delivery date to the customer
          - name : order_estimated_delivery_date
            description: Shows the estimated delivery date that was informed to customer at the purchase moment
      - name: stg_Olist_big_query__product
      - name: stg_Olist_big_query__reviews
      - name: stg_Olist_big_query__sellers
      - name : stg_Olist_big_query__turnover_map
      
      - name : CentralizedData
        description : aggregation of turnover, orders and items by date
        columns:
          - name: date_date
            description: YYYY-MM-DD
          - name: turnover
            description : sum of price and freight values
          - name : total_orders
            description: count distinct of order_id
          - name : total_items
            description: count of order_item_id
          - name : avg_basket
            description: turnover / total_orders
          - name : avg_unit_price 
            description: turnover/ total_items
          - name : turnover_growth_percent 
            description : percentage of turnover growth from previous day
          - name : orders_growth_percent
            description : percentage of orders growth from previous day
      - name : Create_date_date_and_time_time
        description: create date and time-hour columns using column order_purchase_timestamp from order table
        columns:
          - name : order_id
            description: unique identifier of the order
          - name : customer_id
            description: key to the customer dataset. Each order has a unique customer_id
          - name : order_status
            description: Reference to the order status (delivered, shipped, etc)
          - name : order_purchase_timestamp
            description: Shows the purchase timestamp
          - name : order_approved_at
            description : Shows the payment approval timestamp
          - name : order_delivered_carrier_date
            description: Shows the order posting timestamp. When it was handled to the logistic partner.
          - name : order_delivered_customer_date
            description: Shows the actual order delivery date to the customer
          - name : order_estimated_delivery_date
            description: Shows the estimated delivery date that was informed to customer at the purchase moment
          - name: date_date
            description: date of the table YYYY-MM-DD
          - name: time_time
            description: hour of the day
      - name: NPS_calcul
        description: table where every information of the NPS score is
        columns:
          - name: promoters_1
            description: 0 and 1 value where 1 is a customer where review_score equal to 5
          - name : passive
            description: 0 and 1 value where 1 is a customer where review_score equal to 4
          - name : detractors
            description: 0 and 1 value where 1 is a customer where review_score between 1 to 3
      - name: TurnoverAndTotalOrderByDate
        description: turnove and total order group only by day
        columns:
          - name: payment_value
            description: transaction value
          - name : turnover
            description: sum of price and freight values
          - name : total_orders
            description: count distinct of order_id from CentralizedData
          - name : avg_basket
            description: turnover / total_orders
          - name: avg_unit_price
            description: turnover/ total_items
          - name: date_1
            description: YYYY-MM-DD created to have all the date of the calendar
      - name: sellers_table
        description: important table that is used to make calculations and retrieve informations on sellers(don't delete)
        columns:
          - name: date_1
            description: YYYY-MM-DD created to have all the date of the calendar
          - name: order_id
            description: unique identifier of the order
          - name: customer_state
            description: the state that the customer is located
          - name: product_category_name_english
            description: root category of product, translated in English
          - name: product_id
            description: product unique identifier
          - name: payment_value
            description: transaction value
          - name: seller_id
            description: seller unique identifier
          - name: review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
      - name : Top_10_sellers_qty_items
        description: top 10 sellers by number of product sold
        columns:
          - name: seller_id
            description: seller unique identifier
          - name : product_category_name_english
            description: root category of product, translated in English
          - name : number_of_products
            description: number of product sold by sellers in this table
          - name : review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
      - name: Top_10_sellers_value
        description: top 10 sellers by monetary value
        columns:
          - name: seller_id
            description: seller unique identifier
          - name : product_category_name_english
            description: root category of product, translated in English
          - name : seller_total_value
            description: value of the seller in monetary value in the Olist ecosystem
          - name : review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
      - name : ranked_sellers_turnover_categories
        description: sellers ranked by categories and turnover
        columns:
          - name: seller_id
            description: seller unique identifier
          - name: product_category_name_english
            description: root category of product, translated in English
          - name : number_of_orders
            description: number of orders by sellers and category for this table
          - name : number_of_products
            description: number of products by sellers and category for this table
          - name : seller_total_value
            description: value of the seller in monetary value in the Olist ecosystem
          - name : review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
          - name : TOP_10
            description: rank of the sellers by category sales and review_score from top to bottom
      - name : sellers_reviews_percentages
        description: table for having the the percentage of reviews by review_score
        columns:
          - name: seller_id
            description: seller unique identifier
          - name : review_score
            description: Note ranging from 1 to 5 given by the customer on a satisfaction survey
          - name : number_reviews
            description: number of reviews by seller_id
          - name : percentage_of_reviews
            description: percentage of review by seller_id for group by review_score
      - name : sellers_customers_states
              
    
    
    
    
    
    
    
      
    
